export type Cell = "." | "#" | "s" | "~" | "d" | "o";

export type Layout = {
  id: string;
  name: string;
  blurb: string;
  w: number;
  h: number;
  spawn: { x: number; y: number };
  grid: Cell[][];
  indoor: boolean;
};

function parse(id: string, name: string, blurb: string, map: string, indoor = true): Layout {
  const rows = map
    .trim()
    .split("\n")
    .map((r) => r.trim().split("") as Cell[]);
  const h = rows.length;
  const w = rows[0].length;
  let spawn = { x: Math.floor(w / 2), y: Math.floor(h / 2) };
  for (let y = 0; y < h; y++) {
    for (let x = 0; x < w; x++) {
      if (rows[y][x] === "s") {
        spawn = { x, y };
        rows[y][x] = ".";
      }
    }
  }
  return { id, name, blurb, w, h, spawn, grid: rows, indoor };
}

export const LAYOUTS: Layout[] = [
  parse(
    "cozy_studio",
    "Cozy Studio",
    "A tight 8×8 cube. Easy to fill, hard to overstuff.",
    `
........
........
........
........
...s....
........
........
........
`
  ),
  parse(
    "city_loft",
    "City Loft",
    "L-shaped loft with a nook for a desk or bar.",
    `
..........
..........
..........
.....s....
..........
......####
......####
......####
......####
..........
`
  ),
  parse(
    "neon_suite",
    "Neon Suite",
    "Wide 12×10 suite. Room for a lounge and a sleep side.",
    `
............
............
............
............
......s.....
............
............
............
............
............
`
  ),
  parse(
    "sky_penthouse",
    "Sky Penthouse",
    "Indoor lounge plus a sun terrace along the edge.",
    `
..............
..............
..............
..............
.......s......
..............
..............
..............
oooooooooooooo
oooooooooooooo
oooooooooooooo
..............
`
  ),
  parse(
    "vault_den",
    "Vault Den",
    "A square den with a central column — great for a statue.",
    `
..........
..........
..........
...##.....
...##..s..
..........
..........
..........
..........
..........
`
  ),
  parse(
    "garden_lanai",
    "Garden Lanai",
    "A courtyard pad — indoor ring around a sunny garden.",
    `
..........
..........
..oooooo..
..o....o..
..o..s.o..
..o....o..
..oooooo..
..........
..........
..........
`
  ),
  parse(
    "grand_lobby",
    "Grand Lobby",
    "Hotel lobby",
    `
................
................
................
................
................
................
........s.......
................
................
................
................
................
................
................
................
................
`,
    true
  ),
  parse(
    "roof_pool",
    "Roof Pool",
    "Sun deck",
    `
..................
..................
....~~~~~~~~~~....
....~~~~~~~~~~....
....~~~~~~~~~~....
....~~~~~~~~~~....
..................
........s.........
..................
oooooooooooooooooo
oooooooooooooooooo
..................
..................
..................
`,
    false
  ),
  parse(
    "shill_club",
    "SHILL ZONE",
    "Night club",
    `
................
................
....dddddddd....
....dddddddd....
....dddddddd....
....dddddddd....
................
........s.......
................
................
................
................
................
................
`
  ),
  parse(
    "cook_lab",
    "The Cook Room",
    "Think tank",
    `
..............
..............
..............
..............
......s.......
..............
..............
..............
..............
..............
..............
..............
`
  ),
  parse(
    "pixel_arcade",
    "Signal Arcade",
    "Cabinets and dice",
    `
..............
..............
..............
..............
......s.......
..............
..............
..............
..............
..............
..............
..............
`
  ),
];

export const USER_LAYOUTS = LAYOUTS.filter((l) =>
  ["cozy_studio", "city_loft", "neon_suite", "sky_penthouse", "vault_den", "garden_lanai"].includes(l.id)
);

export function layoutById(id: string) {
  return LAYOUTS.find((l) => l.id === id) || LAYOUTS[0];
}

export function walkable(layout: Layout, x: number, y: number) {
  if (y < 0 || x < 0 || y >= layout.h || x >= layout.w) return false;
  const c = layout.grid[y][x];
  return c === "." || c === "s" || c === "d" || c === "o";
}

export function isDance(layout: Layout, x: number, y: number) {
  return layout.grid[y]?.[x] === "d";
}

export function isWater(layout: Layout, x: number, y: number) {
  return layout.grid[y]?.[x] === "~";
}

export function isOutdoor(layout: Layout, x: number, y: number) {
  return layout.grid[y]?.[x] === "o";
}
