export type Cell = "." | "#" | "s" | "~" | "d" | "o" | "1" | "2" | "r" | "e";

export type Layout = {
  id: string;
  name: string;
  blurb: string;
  w: number;
  h: number;
  spawn: { x: number; y: number };
  grid: Cell[][];
  indoor: boolean;
  premium?: boolean;
  price?: number;
  paper?: string;
  floorA?: string;
  floorB?: string;
};

function parse(
  id: string,
  name: string,
  blurb: string,
  map: string,
  extra: Partial<Layout> = {}
): Layout {
  const rows = map
    .trim()
    .split("\n")
    .map((r) => r.trim().split("") as Cell[]);
  const w = Math.max(...rows.map((r) => r.length));
  for (const r of rows) while (r.length < w) r.push("#");
  const h = rows.length;
  let spawn = { x: Math.floor(w / 2), y: Math.floor(h / 2) };
  for (let y = 0; y < h; y++) {
    for (let x = 0; x < w; x++) {
      if (rows[y][x] === "s") {
        spawn = { x, y };
        rows[y][x] = ".";
      }
    }
  }
  if (extra.indoor !== false) placeDoorWestOrNorth(rows, w, h);
  const door = findDoor(rows);
  if (door) spawn = { x: door.x, y: door.y };
  return {
    id,
    name,
    blurb,
    w,
    h,
    spawn,
    grid: rows,
    indoor: extra.indoor !== false,
    premium: extra.premium,
    price: extra.price,
    paper: extra.paper,
    floorA: extra.floorA,
    floorB: extra.floorB,
  };
}

function findDoor(rows: Cell[][]) {
  for (let y = 0; y < rows.length; y++) {
    for (let x = 0; x < (rows[y]?.length || 0); x++) {
      if (rows[y][x] === "e") return { x, y };
    }
  }
  return null;
}

function placeDoorWestOrNorth(rows: Cell[][], w: number, h: number) {
  if (findDoor(rows)) return;
  const west: number[] = [];
  for (let y = 0; y < h; y++) {
    const c = rows[y][0];
    if (c === "." || c === "d" || c === "o" || c === "1" || c === "2" || c === "r") west.push(y);
  }
  if (west.length) {
    rows[west[Math.floor(west.length / 2)]][0] = "e";
    return;
  }
  const north: number[] = [];
  for (let x = 0; x < w; x++) {
    const c = rows[0][x];
    if (c === "." || c === "d" || c === "o" || c === "1" || c === "2" || c === "r") north.push(x);
  }
  if (north.length) rows[0][north[Math.floor(north.length / 2)]] = "e";
}

const ROOM = { paper: "#e8d9c4", floorA: "#d4b48a", floorB: "#c19a6e" };

export const LAYOUTS: Layout[] = [
  parse(
    "cozy_studio",
    "Studio",
    "Simple 10×8 box. Bed on one side, lounge on the other.",
    `
..........
..........
..........
..........
....s.....
..........
..........
..........
`,
    ROOM
  ),
  parse(
    "city_loft",
    "L Loft",
    "Classic L: long living room plus a private wing.",
    `
............
............
............
......s.....
............
............
........####
........####
........####
........####
`,
    ROOM
  ),
  parse(
    "neon_suite",
    "Wide Suite",
    "Open 12×10 rectangle — easy to furnish, lots of floor.",
    `
............
............
............
............
......s.....
............
............
............
............
............
`,
    ROOM
  ),
  parse(
    "sky_penthouse",
    "Long Hall",
    "A 14×7 hall. Line furniture along the walls.",
    `
..............
..............
.......s......
..............
..............
..............
..............
`,
    ROOM
  ),
  parse(
    "garden_lanai",
    "U Court",
    "U-shape: two wings and a court that opens toward the door.",
    `
............
............
............
......s.....
............
............
....####....
....####....
`,
    ROOM
  ),
  parse(
    "vault_den",
    "Twin Rooms",
    "Two rooms joined by a wide doorway. Sleep and sit separately.",
    `
......########
......########
..............
......s.......
..............
########......
########......
`,
    ROOM
  ),

  parse(
    "gold_elbow",
    "Raised Loft",
    "Ground lounge plus a raised platform you climb by stairs.",
    `
..........
..........
....s.....
..........
...rr.....
...11.....
...11.....
...11.....
..........
..........
`,
    { ...ROOM, premium: true, price: 480, paper: "#dcc8a8" }
  ),
  parse(
    "gold_twin",
    "Split L",
    "L-shape with a raised wing. Stairs at the corner.",
    `
............
............
......s.....
............
........rrrr
........1111
........1111
........1111
........####
........####
`,
    { ...ROOM, premium: true, price: 720, paper: "#e0c8b0" }
  ),
  parse(
    "gold_gallery",
    "Mezzanine",
    "Long floor with a raised gallery along the back wall.",
    `
111111111111
111111111111
rr..........
............
......s.....
............
............
............
............
`,
    { ...ROOM, premium: true, price: 980, paper: "#c8b898" }
  ),
  parse(
    "gold_split",
    "Split Level",
    "Lower lounge, stairs, a wide upper bedroom. Two heights, one suite.",
    `
........11111111
........11111111
........11111111
........11111111
........rrrr....
................
......s.........
................
................
............e...
`,
    { ...ROOM, premium: true, price: 1400, paper: "#d4c4a4" }
  ),
  parse(
    "gold_cluster",
    "Terrace Suite",
    "Indoor pad plus a raised terrace through a stair.",
    `
..........
..........
....s.....
..........
....rr....
oooo11oooo
oooo11oooo
oooo11oooo
..........
..........
`,
    { ...ROOM, premium: true, price: 1800, paper: "#c8d4b0", floorA: "#c4b07a", floorB: "#b49e68" }
  ),
  parse(
    "gold_maze",
    "Grand Loft",
    "Two raised stages, two stair runs. Built for showing off.",
    `
1111....1111
1111....1111
rr........rr
............
......s.....
............
............
rr........rr
1111....1111
1111....1111
`,
    { ...ROOM, premium: true, price: 2600, paper: "#e8d0b0" }
  ),

  parse(
    "grand_lobby",
    "Grand Lobby",
    "Hotel lobby",
    `
........11111111
........11111111
........rrrrrrrr
................
................
................
........s.......
................
................
................
................
................
................
................
................
................
`,
    { paper: "#f3e0c4", floorA: "#f6d7c0", floorB: "#e8c4a8" }
  ),
  parse(
    "roof_pool",
    "Roof Pool",
    "Sun deck",
    `
..................
..................
....~~~~~~~~~~~~..
....~~~~~~~~~~~~..
....~~~~~~~~~~~~..
....~~~~~~~~~~~~..
....~~~~~~~~~~~~..
........s.........
..................
oooooooooooooooooo
oooooooooooooooooo
..................
..................
..................
`,
    { indoor: false, paper: "#87d0ea", floorA: "#f0a888", floorB: "#e09070" }
  ),
  parse(
    "shill_club",
    "SHILL ZONE",
    "Night club",
    `
................
................
.....dddddd.....
.....dddddd.....
.....dddddd.....
.....dddddd.....
.....dddddd.....
.....dddddd.....
........s.......
................
................
................
................
................
`,
    { paper: "#4a1d73", floorA: "#2a1444", floorB: "#1a0c30" }
  ),
  parse(
    "cook_lab",
    "The Cook Room",
    "Think tank",
    `
..............
..............
..............
..............
......s.......
..............
..............
..............
..............
..............
..............
..............
`,
    { paper: "#f3ead8", floorA: "#e8d5c4", floorB: "#d4b8a0" }
  ),
  parse(
    "pixel_arcade",
    "Signal Arcade",
    "Cabinets and dice",
    `
..............
..............
..............
..............
......s.......
..............
..............
..............
..............
..............
..............
..............
`,
    { paper: "#3b1d6e", floorA: "#f472b6", floorB: "#38bdf8" }
  ),
];

export const FREE_LAYOUT_IDS = [
  "cozy_studio",
  "city_loft",
  "neon_suite",
  "sky_penthouse",
  "garden_lanai",
  "vault_den",
];

export const USER_LAYOUTS = LAYOUTS.filter((l) => FREE_LAYOUT_IDS.includes(l.id));
export const PREMIUM_LAYOUTS = LAYOUTS.filter((l) => l.premium);

export function layoutById(id: string) {
  return LAYOUTS.find((l) => l.id === id) || LAYOUTS[0];
}

export function walkable(layout: Layout, x: number, y: number) {
  if (y < 0 || x < 0 || y >= layout.h || x >= layout.w) return false;
  const c = layout.grid[y][x];
  return c === "." || c === "s" || c === "d" || c === "o" || c === "1" || c === "2" || c === "r" || c === "e";
}

export function tileH(layout: Layout, x: number, y: number) {
  if (y < 0 || x < 0 || y >= layout.h || x >= layout.w) return 0;
  const c = layout.grid[y][x];
  if (c === "1") return 1.2;
  if (c === "2") return 2.35;
  if (c === "r") return 0.58;
  return 0;
}

export function isStair(layout: Layout, x: number, y: number) {
  return layout.grid[y]?.[x] === "r";
}

export function isDance(layout: Layout, x: number, y: number) {
  return layout.grid[y]?.[x] === "d";
}

export function isWater(layout: Layout, x: number, y: number) {
  return layout.grid[y]?.[x] === "~";
}

export function isOutdoor(layout: Layout, x: number, y: number) {
  return layout.grid[y]?.[x] === "o";
}

export function isDoor(layout: Layout, x: number, y: number) {
  return layout.grid[y]?.[x] === "e";
}

export function ownsLayout(owned: string[] | undefined, layoutId: string) {
  if (FREE_LAYOUT_IDS.includes(layoutId)) return true;
  return !!owned?.includes(layoutId);
}
